apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drone.fullname" . }}-agent
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  DRONE_DEBUG: "false"
