apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drone.fullname" . }}-server
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  DRONE_DEBUG: "false"
  DRONE_DATABASE_DRIVER: "sqlite3"
  DRONE_DATABASE_DATASOURCE: "/var/lib/drone/drone.sqlite"
  DRONE_PROVIDER: "github"
  DRONE_OPEN: "true"
  DRONE_GITHUB: "true"
  DRONE_GITHUB_CLIENT: "githuboauth2clientid"
  # Github oauth2 client id.
  DRONE_GITHUB_SCOPE: "repo,repo:status,user:email,read:org"
  DRONE_GITHUB_GIT_USERNAME: "gitusername"
  DRONE_ADMIN: "gitusername"
  DRONE_GITHUB_PRIVATE_MODE: "false"
  DRONE_GITHUB_MERGE_REF: "true"
  # Set to true to use the refs/pulls/%d/merge vs refs/pulls/%d/head
  DRONE_GITHUB_CONTEXT: "continuous-integration/drone"
  DRONE_GITHUB_SKIP_VERIFY: "true"
