description: Grafana instance for kube-prometheus
engine: gotpl
maintainers:
- email: weiwei.inf@gmail.com
  name: Wei Wei
- email: vglafirov@gmail.com
  name: Vladimir Glafirov
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
name: grafana
sources:
- https://github.com/coreos/prometheus-operator
version: 0.0.31
appVersion: 5.1.2
kubeVersion: "^1.8.0-0"
