{{- if .Values.datadog.collectEvents -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadogtoken
  labels:
    app: {{ template "datadog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  event.tokenKey: "0"
{{- end -}}
