dependencies:
  - name: sidecarInjectorWebhook
    version: 1.0.1
    condition: sidecarInjectorWebhook.enabled
    repository: "file://../charts/sidecarInjectorWebhook"
  - name: security
    version: 1.0.1
    condition: security.enabled
    repository: "file://../charts/security"
  - name: ingress
    version: 1.0.1
    condition: ingress.enabled
    repository: "file://../charts/ingress"
  - name: gateways
    version: 1.0.1
    condition: gateways.enabled
    repository: "file://../charts/gateways"
  - name: mixer
    version: 1.0.1
    condition: mixer.enabled
    repository: "file://../charts/mixer"
  - name: pilot
    version: 1.0.1
    condition: pilot.enabled
    repository: "file://../charts/pilot"
  - name: grafana
    version: 1.0.1
    condition: grafana.enabled
    repository: "file://../charts/grafana"
  - name: prometheus
    version: 1.0.1
    condition: prometheus.enabled
    repository: "file://../charts/prometheus"
  - name: servicegraph
    version: 1.0.1
    condition: servicegraph.enabled
    repository: "file://../charts/servicegraph"
  - name: tracing
    version: 1.0.1
    condition: tracing.enabled
    repository: "file://../charts/tracing"
  - name: galley
    version: 1.0.1
    condition: galley.enabled
    repository: "file://../charts/galley"
  - name: kiali
    version: 1.0.1
    condition: kiali.enabled
    repository: "file://../charts/kiali"
  - name: certmanager
    version: 1.0.1
    condition: certmanager.enabled
    repository: "file://../charts/certmanager"
