{{- if .Values.deployments.etcdOperator }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
  annotations:
    "helm.sh/hook": "crd-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: etcd.database.coreos.com
  scope: Namespaced
  version: v1beta2
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    plural: etcdclusters
    shortNames:
    - etcd
    singular: etcdcluster
{{- end }}
