{{- if .Values.deployments.restoreOperator }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdrestores.etcd.database.coreos.com
  annotations:
    "helm.sh/hook": "crd-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: etcd.database.coreos.com
  scope: Namespaced
  version: v1beta2
  names:
    kind: EtcdRestore
    listKind: EtcdRestoreList
    plural: etcdrestores
    singular: etcdrestore
{{- end }}
