apiVersion: vault.security.coreos.com/v1alpha1
kind: VaultService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  nodes: {{ .Values.vault.node }}
  version: {{ .Values.vault.version }}
