apiVersion: v1
description: Longhorn is a distributed block storage system for Kubernetes powered by Rancher Labs.
name: longhorn
version: 0.1.0
icon: https://s3.us-east-2.amazonaws.com/longhorn-assets/longhorn-logo.svg
appVersion: v0.1.0
maintainers:
- name: rancher
  email: charts@rancher.com
home: https://github.com/rancher/longhorn
