dependencies:
  - name: sidecar-injector
    version: 0.5.0
    condition: sidecar-injector.enabled
    repository: "file://../charts/sidecar-injector"
  - name: ingress
    version: 0.5.0
    condition: ingress.enabled
    repository: "file://../charts/ingress"
  - name: mixer
    version: 0.5.0
    condition: mixer.enabled
    repository: "file://../charts/mixer"
  - name: pilot
    version: 0.5.0
    condition: pilot.enabled
    repository: "file://../charts/pilot"
  - name: security
    version: 0.5.0
    condition: global.securityEnabled
    repository: "file://../charts/security"
  - name: grafana
    version: 0.1.0
    condition: grafana.enabled
    repository: "file://../charts/grafana"
  - name: prometheus
    version: 0.1.0
    condition: prometheus.enabled
    repository: "file://../charts/prometheus"
  - name: servicegraph
    version: 0.1.0
    condition: servicegraph.enabled
    repository: "file://../charts/servicegraph"
  - name: zipkin
    version: 0.1.0
    condition: zipkin.enabled
    repository: "file://../charts/zipkin"
