kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.persistence.defaultClass }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  {{- else }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  {{- end }}
provisioner: rancher.io/{{ .Release.Name }}
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
