name: datadog
version: 1.0.0
appVersion: 6.3.1
description: Datadog Agent
keywords:
- monitoring
- logging
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-agent
maintainers:
- name: janeczku
  email: jan@rancher.com
